TRUNCATE TABLE role_privilege RESTART IDENTITY CASCADE;
TRUNCATE TABLE user_role RESTART IDENTITY CASCADE;
TRUNCATE TABLE role RESTART IDENTITY CASCADE;
TRUNCATE TABLE privilege RESTART IDENTITY CASCADE;

INSERT INTO role (id, name) VALUES (1, 'ADMIN'), (2, 'USER');
INSERT INTO privilege (id, name) VALUES (1, 'READ_PRIVILEGE'), (2, 'WRITE_PRIVILEGE');

INSERT INTO role_privilege (role_id, privilege_id)
VALUES
    (1, 1),
    (1, 2),
    (2, 1);
