TRUNCATE TABLE role_privilege RESTART IDENTITY CASCADE;
TRUNCATE TABLE user_role RESTART IDENTITY CASCADE;
TRUNCATE TABLE role RESTART IDENTITY CASCADE;
TRUNCATE TABLE privilege RESTART IDENTITY CASCADE;

INSERT INTO privilege (id, name) VALUES (1, 'READ_PRIVILEGE');
INSERT INTO privilege (id, name) VALUES (2, 'WRITE_PRIVILEGE');
